Traceback (most recent call last):
  File "C:\Users\XPS\AppData\Roaming\Python\Python312\site-packages\jupyter_core\utils\__init__.py", line 154, in wrapped
    asyncio.get_running_loop()
RuntimeError: no running event loop

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\XPS\AppData\Local\Programs\Python\Python312\Lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\XPS\AppData\Local\Programs\Python\Python312\Lib\site-packages\nbclient\client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XPS\AppData\Roaming\Python\Python312\site-packages\jupyter_core\utils\__init__.py", line 158, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XPS\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\XPS\AppData\Local\Programs\Python\Python312\Lib\site-packages\nbclient\client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "C:\Users\XPS\AppData\Local\Programs\Python\Python312\Lib\site-packages\nbclient\client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\XPS\AppData\Local\Programs\Python\Python312\Lib\site-packages\nbclient\client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import pandas as pd
from fredapi import Fred

fred = Fred(api_key='9c70445138df124be4928605b7e08bd4')

# Pull monetary aggregate data from Fred
m0 = fred.get_series('CURRSL')
mb = fred.get_series('BOGMBASE')
m1 = fred.get_series('M1SL')
m2 = fred.get_series('M2SL')
------------------


[31m---------------------------------------------------------------------------[39m
[31mSSLEOFError[39m                               Traceback (most recent call last)
[36mFile [39m[32m~\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py:1344[39m, in [36mAbstractHTTPHandler.do_open[39m[34m(self, http_class, req, **http_conn_args)[39m
[32m   1343[39m [38;5;28;01mtry[39;00m:
[32m-> [39m[32m1344[39m     [43mh[49m[43m.[49m[43mrequest[49m[43m([49m[43mreq[49m[43m.[49m[43mget_method[49m[43m([49m[43m)[49m[43m,[49m[43m [49m[43mreq[49m[43m.[49m[43mselector[49m[43m,[49m[43m [49m[43mreq[49m[43m.[49m[43mdata[49m[43m,[49m[43m [49m[43mheaders[49m[43m,[49m
[32m   1345[39m [43m              [49m[43mencode_chunked[49m[43m=[49m[43mreq[49m[43m.[49m[43mhas_header[49m[43m([49m[33;43m'[39;49m[33;43mTransfer-encoding[39;49m[33;43m'[39;49m[43m)[49m[43m)[49m
[32m   1346[39m [38;5;28;01mexcept[39;00m [38;5;167;01mOSError[39;00m [38;5;28;01mas[39;00m err: [38;5;66;03m# timeout error[39;00m

[36mFile [39m[32m~\AppData\Local\Programs\Python\Python312\Lib\http\client.py:1336[39m, in [36mHTTPConnection.request[39m[34m(self, method, url, body, headers, encode_chunked)[39m
[32m   1335[39m [38;5;250m[39m[33;03m"""Send a complete request to the server."""[39;00m
[32m-> [39m[32m1336[39m [38;5;28;43mself[39;49m[43m.[49m[43m_send_request[49m[43m([49m[43mmethod[49m[43m,[49m[43m [49m[43murl[49m[43m,[49m[43m [49m[43mbody[49m[43m,[49m[43m [49m[43mheaders[49m[43m,[49m[43m [49m[43mencode_chunked[49m[43m)[49m

[36mFile [39m[32m~\AppData\Local\Programs\Python\Python312\Lib\http\client.py:1382[39m, in [36mHTTPConnection._send_request[39m[34m(self, method, url, body, headers, encode_chunked)[39m
[32m   1381[39m     body = _encode(body, [33m'[39m[33mbody[39m[33m'[39m)
[32m-> [39m[32m1382[39m [38;5;28;43mself[39;49m[43m.[49m[43mendheaders[49m[43m([49m[43mbody[49m[43m,[49m[43m [49m[43mencode_chunked[49m[43m=[49m[43mencode_chunked[49m[43m)[49m

[36mFile [39m[32m~\AppData\Local\Programs\Python\Python312\Lib\http\client.py:1331[39m, in [36mHTTPConnection.endheaders[39m[34m(self, message_body, encode_chunked)[39m
[32m   1330[39m     [38;5;28;01mraise[39;00m CannotSendHeader()
[32m-> [39m[32m1331[39m [38;5;28;43mself[39;49m[43m.[49m[43m_send_output[49m[43m([49m[43mmessage_body[49m[43m,[49m[43m [49m[43mencode_chunked[49m[43m=[49m[43mencode_chunked[49m[43m)[49m

[36mFile [39m[32m~\AppData\Local\Programs\Python\Python312\Lib\http\client.py:1091[39m, in [36mHTTPConnection._send_output[39m[34m(self, message_body, encode_chunked)[39m
[32m   1090[39m [38;5;28;01mdel[39;00m [38;5;28mself[39m._buffer[:]
[32m-> [39m[32m1091[39m [38;5;28;43mself[39;49m[43m.[49m[43msend[49m[43m([49m[43mmsg[49m[43m)[49m
[32m   1093[39m [38;5;28;01mif[39;00m message_body [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m:
[32m   1094[39m 
[32m   1095[39m     [38;5;66;03m# create a consistent interface to message_body[39;00m

[36mFile [39m[32m~\AppData\Local\Programs\Python\Python312\Lib\http\client.py:1035[39m, in [36mHTTPConnection.send[39m[34m(self, data)[39m
[32m   1034[39m [38;5;28;01mif[39;00m [38;5;28mself[39m.auto_open:
[32m-> [39m[32m1035[39m     [38;5;28;43mself[39;49m[43m.[49m[43mconnect[49m[43m([49m[43m)[49m
[32m   1036[39m [38;5;28;01melse[39;00m:

[36mFile [39m[32m~\AppData\Local\Programs\Python\Python312\Lib\http\client.py:1477[39m, in [36mHTTPSConnection.connect[39m[34m(self)[39m
[32m   1475[39m     server_hostname = [38;5;28mself[39m.host
[32m-> [39m[32m1477[39m [38;5;28mself[39m.sock = [38;5;28;43mself[39;49m[43m.[49m[43m_context[49m[43m.[49m[43mwrap_socket[49m[43m([49m[38;5;28;43mself[39;49m[43m.[49m[43msock[49m[43m,[49m
[32m   1478[39m [43m                                      [49m[43mserver_hostname[49m[43m=[49m[43mserver_hostname[49m[43m)[49m

[36mFile [39m[32m~\AppData\Local\Programs\Python\Python312\Lib\ssl.py:455[39m, in [36mSSLContext.wrap_socket[39m[34m(self, sock, server_side, do_handshake_on_connect, suppress_ragged_eofs, server_hostname, session)[39m
[32m    449[39m [38;5;28;01mdef[39;00m[38;5;250m [39m[34mwrap_socket[39m([38;5;28mself[39m, sock, server_side=[38;5;28;01mFalse[39;00m,
[32m    450[39m                 do_handshake_on_connect=[38;5;28;01mTrue[39;00m,
[32m    451[39m                 suppress_ragged_eofs=[38;5;28;01mTrue[39;00m,
[32m    452[39m                 server_hostname=[38;5;28;01mNone[39;00m, session=[38;5;28;01mNone[39;00m):
[32m    453[39m     [38;5;66;03m# SSLSocket class handles server_hostname encoding before it calls[39;00m
[32m    454[39m     [38;5;66;03m# ctx._wrap_socket()[39;00m
[32m--> [39m[32m455[39m     [38;5;28;01mreturn[39;00m [38;5;28;43mself[39;49m[43m.[49m[43msslsocket_class[49m[43m.[49m[43m_create[49m[43m([49m
[32m    456[39m [43m        [49m[43msock[49m[43m=[49m[43msock[49m[43m,[49m
[32m    457[39m [43m        [49m[43mserver_side[49m[43m=[49m[43mserver_side[49m[43m,[49m
[32m    458[39m [43m        [49m[43mdo_handshake_on_connect[49m[43m=[49m[43mdo_handshake_on_connect[49m[43m,[49m
[32m    459[39m [43m        [49m[43msuppress_ragged_eofs[49m[43m=[49m[43msuppress_ragged_eofs[49m[43m,[49m
[32m    460[39m [43m        [49m[43mserver_hostname[49m[43m=[49m[43mserver_hostname[49m[43m,[49m
[32m    461[39m [43m        [49m[43mcontext[49m[43m=[49m[38;5;28;43mself[39;49m[43m,[49m
[32m    462[39m [43m        [49m[43msession[49m[43m=[49m[43msession[49m
[32m    463[39m [43m    [49m[43m)[49m

[36mFile [39m[32m~\AppData\Local\Programs\Python\Python312\Lib\ssl.py:1042[39m, in [36mSSLSocket._create[39m[34m(cls, sock, server_side, do_handshake_on_connect, suppress_ragged_eofs, server_hostname, context, session)[39m
[32m   1041[39m                 [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m([33m"[39m[33mdo_handshake_on_connect should not be specified for non-blocking sockets[39m[33m"[39m)
[32m-> [39m[32m1042[39m             [38;5;28;43mself[39;49m[43m.[49m[43mdo_handshake[49m[43m([49m[43m)[49m
[32m   1043[39m [38;5;28;01mexcept[39;00m:

[36mFile [39m[32m~\AppData\Local\Programs\Python\Python312\Lib\ssl.py:1320[39m, in [36mSSLSocket.do_handshake[39m[34m(self, block)[39m
[32m   1319[39m         [38;5;28mself[39m.settimeout([38;5;28;01mNone[39;00m)
[32m-> [39m[32m1320[39m     [38;5;28;43mself[39;49m[43m.[49m[43m_sslobj[49m[43m.[49m[43mdo_handshake[49m[43m([49m[43m)[49m
[32m   1321[39m [38;5;28;01mfinally[39;00m:

[31mSSLEOFError[39m: [SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)

During handling of the above exception, another exception occurred:

[31mURLError[39m                                  Traceback (most recent call last)
[36mCell[39m[36m [39m[32mIn[3][39m[32m, line 10[39m
[32m      8[39m mb = fred.get_series([33m'[39m[33mBOGMBASE[39m[33m'[39m)
[32m      9[39m m1 = fred.get_series([33m'[39m[33mM1SL[39m[33m'[39m)
[32m---> [39m[32m10[39m m2 = [43mfred[49m[43m.[49m[43mget_series[49m[43m([49m[33;43m'[39;49m[33;43mM2SL[39;49m[33;43m'[39;49m[43m)[49m

[36mFile [39m[32m~\AppData\Local\Programs\Python\Python312\Lib\site-packages\fredapi\fred.py:151[39m, in [36mFred.get_series[39m[34m(self, series_id, observation_start, observation_end, **kwargs)[39m
[32m    149[39m [38;5;28;01mif[39;00m kwargs.keys():
[32m    150[39m     url += [33m'[39m[33m&[39m[33m'[39m + urlencode(kwargs)
[32m--> [39m[32m151[39m root = [38;5;28;43mself[39;49m[43m.[49m[43m__fetch_data[49m[43m([49m[43murl[49m[43m)[49m
[32m    152[39m [38;5;28;01mif[39;00m root [38;5;129;01mis[39;00m [38;5;28;01mNone[39;00m:
[32m    153[39m     [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m([33m'[39m[33mNo data exists for series id: [39m[33m'[39m + series_id)

[36mFile [39m[32m~\AppData\Local\Programs\Python\Python312\Lib\site-packages\fredapi\fred.py:84[39m, in [36mFred.__fetch_data[39m[34m(self, url)[39m
[32m     82[39m url += [33m'[39m[33m&api_key=[39m[33m'[39m + [38;5;28mself[39m.api_key
[32m     83[39m [38;5;28;01mtry[39;00m:
[32m---> [39m[32m84[39m     response = [43murlopen[49m[43m([49m[43murl[49m[43m)[49m
[32m     85[39m     root = ET.fromstring(response.read())
[32m     86[39m [38;5;28;01mexcept[39;00m HTTPError [38;5;28;01mas[39;00m exc:

[36mFile [39m[32m~\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py:215[39m, in [36murlopen[39m[34m(url, data, timeout, cafile, capath, cadefault, context)[39m
[32m    213[39m [38;5;28;01melse[39;00m:
[32m    214[39m     opener = _opener
[32m--> [39m[32m215[39m [38;5;28;01mreturn[39;00m [43mopener[49m[43m.[49m[43mopen[49m[43m([49m[43murl[49m[43m,[49m[43m [49m[43mdata[49m[43m,[49m[43m [49m[43mtimeout[49m[43m)[49m

[36mFile [39m[32m~\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py:515[39m, in [36mOpenerDirector.open[39m[34m(self, fullurl, data, timeout)[39m
[32m    512[39m     req = meth(req)
[32m    514[39m sys.audit([33m'[39m[33murllib.Request[39m[33m'[39m, req.full_url, req.data, req.headers, req.get_method())
[32m--> [39m[32m515[39m response = [38;5;28;43mself[39;49m[43m.[49m[43m_open[49m[43m([49m[43mreq[49m[43m,[49m[43m [49m[43mdata[49m[43m)[49m
[32m    517[39m [38;5;66;03m# post-process response[39;00m
[32m    518[39m meth_name = protocol+[33m"[39m[33m_response[39m[33m"[39m

[36mFile [39m[32m~\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py:532[39m, in [36mOpenerDirector._open[39m[34m(self, req, data)[39m
[32m    529[39m     [38;5;28;01mreturn[39;00m result
[32m    531[39m protocol = req.type
[32m--> [39m[32m532[39m result = [38;5;28;43mself[39;49m[43m.[49m[43m_call_chain[49m[43m([49m[38;5;28;43mself[39;49m[43m.[49m[43mhandle_open[49m[43m,[49m[43m [49m[43mprotocol[49m[43m,[49m[43m [49m[43mprotocol[49m[43m [49m[43m+[49m
[32m    533[39m [43m                          [49m[33;43m'[39;49m[33;43m_open[39;49m[33;43m'[39;49m[43m,[49m[43m [49m[43mreq[49m[43m)[49m
[32m    534[39m [38;5;28;01mif[39;00m result:
[32m    535[39m     [38;5;28;01mreturn[39;00m result

[36mFile [39m[32m~\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py:492[39m, in [36mOpenerDirector._call_chain[39m[34m(self, chain, kind, meth_name, *args)[39m
[32m    490[39m [38;5;28;01mfor[39;00m handler [38;5;129;01min[39;00m handlers:
[32m    491[39m     func = [38;5;28mgetattr[39m(handler, meth_name)
[32m--> [39m[32m492[39m     result = [43mfunc[49m[43m([49m[43m*[49m[43margs[49m[43m)[49m
[32m    493[39m     [38;5;28;01mif[39;00m result [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m:
[32m    494[39m         [38;5;28;01mreturn[39;00m result

[36mFile [39m[32m~\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py:1392[39m, in [36mHTTPSHandler.https_open[39m[34m(self, req)[39m
[32m   1391[39m [38;5;28;01mdef[39;00m[38;5;250m [39m[34mhttps_open[39m([38;5;28mself[39m, req):
[32m-> [39m[32m1392[39m     [38;5;28;01mreturn[39;00m [38;5;28;43mself[39;49m[43m.[49m[43mdo_open[49m[43m([49m[43mhttp[49m[43m.[49m[43mclient[49m[43m.[49m[43mHTTPSConnection[49m[43m,[49m[43m [49m[43mreq[49m[43m,[49m
[32m   1393[39m [43m                        [49m[43mcontext[49m[43m=[49m[38;5;28;43mself[39;49m[43m.[49m[43m_context[49m[43m)[49m

[36mFile [39m[32m~\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py:1347[39m, in [36mAbstractHTTPHandler.do_open[39m[34m(self, http_class, req, **http_conn_args)[39m
[32m   1344[39m         h.request(req.get_method(), req.selector, req.data, headers,
[32m   1345[39m                   encode_chunked=req.has_header([33m'[39m[33mTransfer-encoding[39m[33m'[39m))
[32m   1346[39m     [38;5;28;01mexcept[39;00m [38;5;167;01mOSError[39;00m [38;5;28;01mas[39;00m err: [38;5;66;03m# timeout error[39;00m
[32m-> [39m[32m1347[39m         [38;5;28;01mraise[39;00m URLError(err)
[32m   1348[39m     r = h.getresponse()
[32m   1349[39m [38;5;28;01mexcept[39;00m:

[31mURLError[39m: <urlopen error [SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)>

